[nfs]
172.31.89.246 ansible_ssh_user='ec2-user'

[webservers]
172.31.87.99 ansible_ssh_user='ec2-user'
172.31.88.161 ansible_ssh_user='ec2-user'

[db]
172.31.89.251 ansible_ssh_user='ubuntu' 

[lb]
172.31.83.27 ansible_ssh_user='ubuntu'
